vich_uploader:
  db_driver: orm

  mappings:
    driver_image:
      uri_prefix: '%app.path.driver_image%'
      upload_destination: '%kernel.project_dir%/public%app.path.driver_image%'
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: false
      namer: vich_uploader.namer_origname

    championship_banner:
      uri_prefix:         '%app.path.championship_banner%'
      upload_destination: '%kernel.project_dir%/public%app.path.championship_banner%'
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: false
      namer: vich_uploader.namer_origname

    event_banner:
      uri_prefix:         '%app.path.event_banner%'
      upload_destination: '%kernel.project_dir%/public%app.path.event_banner%'
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: false
      namer: vich_uploader.namer_origname

    section_banner:
      uri_prefix:         '%app.path.section_banner%'
      upload_destination: '%kernel.project_dir%/public%app.path.section_banner%'
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: false
      namer: vich_uploader.namer_origname

    document_files:
      uri_prefix: '%app.path.document_files%'
      upload_destination: '%kernel.project_dir%/public%app.path.document_files%'
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: false
      namer: vich_uploader.namer_origname





