<?php


namespace App\Controller\Admin;


use App\Entity\Result;
use Symfony\Component\HttpFoundation\JsonResponse;

class ResultAdminController extends DefaultAdminController
{

    public function resetDnfAction($id)
    {
        $object = $this->getDoctrine()->getRepository(Result::class)->findOneById($id);

        $this->admin->resetDnf();
        $this->addFlash('sonata_flash_success', "The driver's DNF reset was successfully completed.");
        $request = $this->getRequest();
        $request->query->set('btn_reset_dnf', true);
        return $this->redirectTo($object);
    }


    public function listAction()
    {

        return parent::listAction(); // TODO: Change the autogenerated stub
    }

    private function redirectToResultTab($request,$object)
    {
        $parameters = ['_tab' => $request->get('_tab')];
        return $this->redirect($this->admin->generateObjectUrl('list', $object, $parameters));
    }

    protected function redirectTo($object)
    {
        $request = $this->getRequest();

        if ($object && $request->get('btn_update_and_list') !== null && $object->getSection()->getEvent()->getResultType() === Result::CUMULATIVE) {
           return $this->redirectToResultTab($request,$object);
        }
        if ( $request->query->get('btn_reset_dnf')){
           return $this->redirectToResultTab($request,$object);
        }

        return parent::redirectTo($object);
    }
}